### ISSUE TITLE
ToDo before calibration

### ISSUE THREAD

**Issue by julemai** [WeiZhiWater/Wetland_hydro#1]
A list of things to address. Order does not match priorities.

- [ ] Make repo private
- [ ] Add pytest
- [ ] Make main() into function `def run_wetland(setup_files, forcing_files, parameters)` returning RMSE. First two arguments are filenames. Third is list of parameters (best dictionary). Draft of those files below.
- [ ] Rethink reading from forcing file. If that file gets bigger it's very inefficient to read all and then extract one basin. Better to split that file into basins such that all we read we also will need.
- [ ] Highly dangerous reading of files, i.e. `wetland_SAmax = SAmax.loc[wetland_id-1, 'SAmax_m2']` and `monthly_data.loc[t_int - 1, ...]`. Assumes those IDs and their order etc.
- [ ] Dont device by integers, e.g., `temp_Q/1000` should be `temp_Q/1000.0`

Draft: "setup_file.txt"
```
wetland_id = w191_vol     # as referenced in forcing_file, e.g. "monthly_input.csv" 
SAmax = 57706.9812        # value in SAmax.csv (line id+1 ?)
initial_volume = 100.0    # initial volume [m3]
tmax = 380                # number of months to simulate
```

Draft: parameter dictionary
```
parameters = { 
     'k' : 0.5,    # streamflow release coefficient
     'r' : 5.0,    # catchment to wetland ratio
}
```

Draft: tests/test_1_wetland
